/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity;

public class SpannerPostgreSQLIdentityColumnSupport extends PostgreSQLIdentityColumnSupport{

	public static final SpannerPostgreSQLIdentityColumnSupport INSTANCE = new SpannerPostgreSQLIdentityColumnSupport();

	public SpannerPostgreSQLIdentityColumnSupport() {
		super();
	}

	@Override
	public String getIdentityColumnString(int type) {
		return "generated by default as identity (BIT_REVERSED_POSITIVE)";
	}
}
