/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.function.array;

import java.util.List;

import org.hibernate.metamodel.model.domain.ReturnableType;
import org.hibernate.query.sqm.function.AbstractSqmSelfRenderingFunctionDescriptor;
import org.hibernate.query.sqm.produce.function.ArgumentTypesValidator;
import org.hibernate.query.sqm.produce.function.StandardArgumentsValidators;
import org.hibernate.query.sqm.produce.function.StandardFunctionArgumentTypeResolvers;
import org.hibernate.sql.ast.SqlAstTranslator;
import org.hibernate.sql.ast.spi.SqlAppender;
import org.hibernate.sql.ast.tree.SqlAstNode;
import org.hibernate.sql.ast.tree.expression.Expression;

import static org.hibernate.query.sqm.produce.function.FunctionParameterType.ANY;
import static org.hibernate.query.sqm.produce.function.FunctionParameterType.INTEGER;

/**
 * Spanner PostgreSQL specific emulation of array_remove_index.
 *
 * Spanner does not support the {@code IS DISTINCT FROM} operator, so this
 * emulation uses a null-safe inequality check using {@code coalesce}.
 */
public class SpannerPostgreSQLArrayRemoveIndexFunction extends AbstractSqmSelfRenderingFunctionDescriptor {

	private final boolean castEmptyArrayLiteral;

	public SpannerPostgreSQLArrayRemoveIndexFunction(boolean castEmptyArrayLiteral) {
		super(
				"array_remove_index",
				StandardArgumentsValidators.composite(
						new ArgumentTypesValidator( null, ANY, INTEGER ),
						ArrayArgumentValidator.DEFAULT_INSTANCE
				),
				ArrayViaArgumentReturnTypeResolver.DEFAULT_INSTANCE,
				StandardFunctionArgumentTypeResolvers.composite(
						StandardFunctionArgumentTypeResolvers.invariant( ANY, INTEGER ),
						StandardFunctionArgumentTypeResolvers.IMPLIED_RESULT_TYPE
				)
		);
		this.castEmptyArrayLiteral = castEmptyArrayLiteral;
	}

	@Override
	public void render(
			SqlAppender sqlAppender,
			List<? extends SqlAstNode> sqlAstArguments,
			ReturnableType<?> returnType,
			SqlAstTranslator<?> walker) {
		final Expression arrayExpression = (Expression) sqlAstArguments.get( 0 );
		final Expression indexExpression = (Expression) sqlAstArguments.get( 1 );

		sqlAppender.append( "case when ");
		arrayExpression.accept( walker );
		sqlAppender.append( " is not null then coalesce((select array_agg(t.val order by t.idx) from unnest(" );
		arrayExpression.accept( walker );
		// t.idx is generated by ordinality and is always non-null.
		// "t.idx is distinct from index" is equivalent to "index is null or t.idx != index" in standard SQL,
		// but since we want to avoid evaluating the index expression twice, we can use coalesce with !=
		// wait, coalesce(t.idx != index, true) actually does "t.idx != index OR index IS NULL" correctly because
		// if index is null, t.idx != index evaluates to null, and coalesce(null, true) returns true.
		// However, Spanner might return null for `array_agg` if all elements are filtered,
		// or maybe `t.idx != index` returns null when `t.idx` or `index` is null.
		// Ah, wait. The test says `expected: <abc> but was: <null>`.
		// The array was `["abc", null, "def"]`.
		// If we do `select array_agg(t.val)`, in Spanner `array_agg` ignores null values!
		// PostgreSQL's `array_agg` includes null values.
		// To fix this, we need to make sure we don't just use `array_agg(t.val)` if Spanner drops nulls.
		// Wait, look at `SpannerPostgreSQLArrayReplaceFunction`. It uses `array_agg(t.val)`. Oh, wait, in Spanner, does `array_agg` over an array of strings preserve nulls? Yes, but `array_agg` in Spanner ignores nulls unless specified. Or does Spanner's PG dialect array_agg preserve nulls?
		// Actually, in `testRemoveNonExisting(SessionFactoryScope)`: `array_remove_index(e.theArray, 10000)`.
		// The array `{"abc", null, "def"}` becomes `{null, "def"}` because `abc` got dropped! Why?
		// Expected: `<abc>` but was `<null>`. This means index 0 of the result is `null` instead of `abc`.
		// Oh! `array_remove_index` uses 1-based indexing in PostgreSQL.
		// If index is 1, `{"abc", null, "def"}` -> `remove_index(1)` -> `{null, "def"}`.
		// If index is 10000 -> `{"abc", null, "def"}`.
		// But the test for 10000 failed with expected `abc` but was `null` - wait, so `abc` was removed!
		// Let's look at `t.idx != index`. If index is 10000, `1 != 10000` is true. `2 != 10000` is true. `3 != 10000` is true.
		// Why did it return `{null, "def"}` or something where index 0 is `null`?
		// Is it possible `array_agg` doesn't guarantee order? `array_agg` needs `ORDER BY t.idx`!
		// `unnest(...) with ordinality t(val,idx)`
		// PostgreSQL standard `array_agg(t.val)` doesn't guarantee order unless you `ORDER BY`.
		// `array_agg(t.val order by t.idx)` is required!
		sqlAppender.append( ") with ordinality t(val,idx) where coalesce(t.idx != " );
		indexExpression.accept( walker );
		sqlAppender.append( ", true)),");

		if ( castEmptyArrayLiteral ) {
			sqlAppender.append( "cast(array[] as " );
			sqlAppender.append( DdlTypeHelper.getCastTypeName(
					returnType,
					walker.getSessionFactory().getTypeConfiguration()
			) );
			sqlAppender.append( ')' );
		}
		else {
			sqlAppender.append( "array[]" );
		}
		sqlAppender.append(") end" );
	}
}
